# Generated by Django 4.0 on 2021-12-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automatas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automata',
            old_name='regexp',
            new_name='word_checked',
        ),
    ]
